### ISSUE TITLE
Indentation broken when folding heading followed by list

### ISSUE THREAD

**Issue by nokola** [laobubu/HyperMD#25]
Steps to reproduce:
1. Open https://laobubu.net/HyperMD/
2. Paste:
```
# Test folding indent
1. Ensure test cert in player settings is not expired. Create new one if needed
```
3. Fold top heading

Expected:
All OK

Actual:
heading is folded but also offsets incorrectly
![image](https://user-images.githubusercontent.com/6869225/40220277-7bc59d82-5a2d-11e8-9fb0-34ba39223d6f.png)

**Comment by laobubu** [comment]
Seems it is a bug of CodeMirror. List lines' style is unexpectedly merged to header lines'.

Add a normal paragraph after the list and everything goes correctly.

**Comment by laobubu** [comment]
```css
pre.HyperMD-header {
  padding-left: 0 !important
}
pre.HyperMD-header  > span > span:first-child {
 margin-left: 0 !important
}
```

Not sure if this works. Written on my phone

**Comment by nokola** [comment]
yes, works, thanks for the response.
Found another, maybe related issue:

## H2
test
```
code
```
## H2

The H2 appears broken style if it ends with code:
![image](https://user-images.githubusercontent.com/6869225/40253085-4c17b500-5a93-11e8-9a27-138656e63d28.png)

**Comment by laobubu** [comment]
When content is folded, the style of last line is merged to the heading line. Therefore, to fix this, give header line's style higher priority, like ....

```css
.cm-s-hypermd-light pre.HyperMD-header {
    line-height: 1.5 !important;
    font-family: inherit !important;
    border: 0 !important;
}
```

Hmmm... anyway, it works.
