### ISSUE TITLE
快速开始案例中使用打包器的方法中引用的你的css文件的高度固定为300px

### ISSUE THREAD

**Issue by Martin1024** [laobubu/HyperMD#47]
你提供的文档中的快速开始案例：http://laobubu.net/HyperMD/?directOpen#./docs/zh-CN/index.md
我使用的用parcel打包的方法，运行效果：

![运行效果](https://user-images.githubusercontent.com/24665332/44944134-0dd58780-ae04-11e8-95ea-3c4b2efece84.png)

查看网页源代码：
``` html
<!DOCTYPE HTML>
<html>
  <head>
    <title>绝赞编辑器</title>
  <link rel="stylesheet" href="/web-editor.60694ee1.css"></head>
  <body>
    <textarea id="myTextarea" height="1000px"># Hello World</textarea>

    <script src="/web-editor.60694ee1.js"></script>
  </body>
</html>
```
点击[链接](http://localhost:1234/web-editor.60694ee1.css)查看 ` /web-editor.60694ee1.css ` 发现文件开头：
``` css
/* BASICS */

.CodeMirror {
  /* Set height, width, borders, and global font properties here */
  font-family: monospace;
  height: 300px;
  color: black;
  direction: ltr;
}
```
这个高度300px应该不合理吧？你能在云端改下这个css文件吗？
或者请问我在本地可以通过什么方法改变文本框高度吗？（我刚刚入门，不是很懂）
